// Generated by tool/agents/generate_certification.py; do not edit.
// Exact docs/verification/agent-certification-matrix.json snapshot.
const agentCertificationBundledJson = r'''{
 "updated": "2026-10-07 (late)",
 "device": "emulator-5554 (OC_API35), not the owner phone",
 "columns": [
  {
   "id": "install",
   "means": "Installs from the pinned download, checksum verified"
  },
  {
   "id": "version",
   "means": "Reports the pinned version on the phone"
  },
  {
   "id": "signedOut",
   "means": "Signed-out state detected and named (no endless \"Checking\")"
  },
  {
   "id": "signIn",
   "means": "Sign-in completes on the phone and the probe confirms it"
  },
  {
   "id": "models",
   "means": "Model list loads and a model can be picked"
  },
  {
   "id": "smoke",
   "means": "A plain prompt gets a streamed reply"
  },
  {
   "id": "tools",
   "means": "A tool call runs and shows as a tool row"
  },
  {
   "id": "permission",
   "means": "An approval request shows, Allow and Deny both work"
  },
  {
   "id": "images",
   "means": "A photo sent to the agent (composer or photo card) reaches it and it answers about it"
  },
  {
   "id": "abort",
   "means": "Stop ends the turn and the agent stays usable"
  },
  {
   "id": "resume",
   "means": "After killing the app/helper the old chat reopens and continues"
  },
  {
   "id": "network",
   "means": "Turning the network off then on recovers the turn or says why"
  },
  {
   "id": "cards",
   "means": "Agent cards (oc-ui show) answered from chat and from the list"
  }
 ],
 "rule": "An agent is certified only when every cell is pass (or n/a with a reason). Capabilities (resume, models, permissions, images, cancel) are granted from pass cells only (BA4).",
 "agents": [
  {
   "id": "claude",
   "name": "Claude Code",
   "route": "Paseo native",
   "cells": {
    "install": {
     "state": "pass",
     "evidence": "docs/verification/agents-on-phone-2026-10-03.md"
    },
    "version": {
     "state": "pass",
     "evidence": "docs/verification/agents-on-phone-2026-10-03.md"
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "untested",
     "evidence": null
    },
    "models": {
     "state": "pass",
     "evidence": "docs/qa/FQ2-2026-10-07/README.md"
    },
    "smoke": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md"
    },
    "tools": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md"
    },
    "permission": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md #2"
    },
    "abort": {
     "state": "pass",
     "evidence": "docs/qa/FQ2-2026-10-07/README.md"
    },
    "resume": {
     "state": "pass",
     "evidence": "docs/qa/FQ2-2026-10-07/README.md"
    },
    "network": {
     "state": "untested",
     "evidence": null
    },
    "cards": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md #5"
    },
    "images": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md#5"
    }
   },
   "agentVersion": "2.1.283",
   "helperVersion": "0.9.2"
  },
  {
   "id": "opencode",
   "name": "OpenCode 1",
   "route": "OpenCode 1 server",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "untested",
     "evidence": null
    },
    "models": {
     "state": "untested",
     "evidence": null
    },
    "smoke": {
     "state": "pass",
     "evidence": "docs/qa/agent-tools-2026-10-07/README.md #6"
    },
    "tools": {
     "state": "untested",
     "evidence": null
    },
    "permission": {
     "state": "untested",
     "evidence": null
    },
    "abort": {
     "state": "untested",
     "evidence": null
    },
    "resume": {
     "state": "untested",
     "evidence": null
    },
    "network": {
     "state": "untested",
     "evidence": null
    },
    "cards": {
     "state": "pass",
     "evidence": "docs/qa/BA5-BA6-device-2026-10-07/README.md"
    },
    "images": {
     "state": "untested",
     "evidence": null
    }
   },
   "agentVersion": "1.18.32",
   "protocolCertification": {
    "scope": "in-app Ubuntu protocol; no UI/restart/install qualification",
    "expectedVersion": "1.18.32",
    "observedVersion": "1.18.32",
    "deviceBuild": 2196,
    "runID": "fq3-20261008b-cert",
    "evidence": "docs/qa/FQ3b-2026-10-08/fq3-20261008b-cert.json",
    "capabilities": {
     "version": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "healthy": true,
       "asserted": true
      }
     },
     "create": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "retained": true,
       "asserted": true
      }
     },
     "models": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "connectedModels": 18,
       "asserted": true
      }
     },
     "stream": {
      "state": "fail",
      "code": "oc1_prompt_error",
      "facts": {}
     },
     "reconnect": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "refetched": true,
       "messages": 2,
       "asserted": true
      }
     },
     "modelSwitch": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "selectionObserved": true,
       "asserted": true
      }
     },
     "abort": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "interrupted": true,
       "usableAfterAbort": true,
       "asserted": true
      }
     },
     "permissionAllow": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "requestObserved": true,
       "replyObserved": true,
       "asserted": true
      }
     },
     "permissionDeny": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "requestObserved": true,
       "replyObserved": true,
       "asserted": true
      }
     },
     "image": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "imageAnswerVerified": true,
       "asserted": true
      }
     },
     "cards": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "cardsToolCall": true,
       "answerReceipt": true,
       "asserted": true
      }
     },
     "protocolSwitch": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "asserted": true,
       "bothHistoriesPreserved": true,
       "freshClients": true,
       "oc1Sessions": 16,
       "oc2Sessions": 16
      }
     }
    },
    "modelSelection": {
     "source": "explicit",
     "requested": "zai-coding-plan/glm-5.3"
    }
   }
  },
  {
   "id": "opencode2",
   "name": "OpenCode 2",
   "route": "OpenCode 2 server",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "untested",
     "evidence": null
    },
    "models": {
     "state": "untested",
     "evidence": null
    },
    "smoke": {
     "state": "untested",
     "evidence": null
    },
    "tools": {
     "state": "untested",
     "evidence": null
    },
    "permission": {
     "state": "pass",
     "evidence": "docs/verification/oc2-forms-device-2026-10-07.md (forms)"
    },
    "abort": {
     "state": "untested",
     "evidence": null
    },
    "resume": {
     "state": "untested",
     "evidence": null
    },
    "network": {
     "state": "untested",
     "evidence": null
    },
    "cards": {
     "state": "off",
     "evidence": "BA6"
    },
    "images": {
     "state": "untested",
     "evidence": null
    }
   },
   "protocolCertification": {
    "scope": "in-app Ubuntu protocol; no UI/restart/install qualification",
    "expectedVersion": "2.0.10",
    "observedVersion": "2.0.10",
    "deviceBuild": 2196,
    "runID": "fq3-20261008b-cert",
    "evidence": "docs/qa/FQ3b-2026-10-08/fq3-20261008b-cert.json",
    "capabilities": {
     "version": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "healthy": true,
       "asserted": true
      }
     },
     "create": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "created": true,
       "asserted": true
      }
     },
     "models": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "enabledModels": 11,
       "selectedModelAvailable": true,
       "asserted": true
      }
     },
     "stream": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "streamedDelta": true,
       "completedReply": true,
       "asserted": true
      }
     },
     "reconnect": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "refetched": true,
       "retainedMessages": 3,
       "asserted": true
      }
     },
     "modelSwitch": {
      "state": "fail",
      "code": "timeout",
      "facts": {}
     },
     "abort": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "interrupted": true,
       "usableAfterAbort": true,
       "midStreamObserved": true,
       "asserted": true
      }
     },
     "permissionAllow": {
      "state": "fail",
      "code": "timeout",
      "facts": {}
     },
     "permissionDeny": {
      "state": "fail",
      "code": "timeout",
      "facts": {}
     },
     "image": {
      "state": "fail",
      "code": "timeout",
      "facts": {}
     },
     "cards": {
      "state": "fail",
      "code": "cards_tool_call_missing",
      "facts": {}
     },
     "protocolSwitch": {
      "state": "pass",
      "code": "verified",
      "facts": {
       "asserted": true,
       "bothHistoriesPreserved": true,
       "freshClients": true,
       "oc1Sessions": 16,
       "oc2Sessions": 16
      }
     }
    },
    "modelSelection": {
     "source": "explicit",
     "requested": "opencode/big-pickle"
    }
   }
  },
  {
   "id": "fx",
   "name": "fx",
   "route": "ACP via Paseo",
   "cells": {
    "install": {
     "state": "pass",
     "evidence": "#95 run, APK 2187"
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "pass",
     "evidence": "#95 run, APK 2187"
    },
    "signIn": {
     "state": "partial",
     "evidence": "reaches the Vercel device page; account needed (OW1)"
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   },
   "agentVersion": "0.0.12",
   "helperVersion": "0.9.2"
  },
  {
   "id": "codex",
   "name": "Codex",
   "route": "Paseo native",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   }
  },
  {
   "id": "gemini",
   "name": "Gemini CLI",
   "route": "ACP via Paseo",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   }
  },
  {
   "id": "qwen",
   "name": "Qwen Code",
   "route": "ACP via Paseo",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   }
  },
  {
   "id": "goose",
   "name": "Goose",
   "route": "ACP via Paseo",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   }
  },
  {
   "id": "omp-acp",
   "name": "Oh My Pi",
   "route": "ACP via Paseo",
   "cells": {
    "install": {
     "state": "untested",
     "evidence": null
    },
    "version": {
     "state": "untested",
     "evidence": null
    },
    "signedOut": {
     "state": "untested",
     "evidence": null
    },
    "signIn": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "models": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "smoke": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "tools": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "permission": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "abort": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "resume": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "network": {
     "state": "blocked:OW1",
     "evidence": null
    },
    "cards": {
     "state": "n/a",
     "evidence": "no cards adapter yet"
    },
    "images": {
     "state": "blocked:OW1",
     "evidence": null
    }
   }
  }
 ],
 "metadata": "agentVersion = the catalog pin the evidence ran on; helperVersion = the Paseo helper it ran through; architecture omitted = holds on every CPU (coordinator decision, protocol-level evidence)."
}
''';
