#!/usr/bin/env python3
"""Bundle the reviewed matrix verbatim; --check detects unbundled evidence edits."""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    source = root / "docs/verification/agent-certification-matrix.json"
    target = root / "lib/domain/agent_tools/agent_certification_snapshot.dart"
    matrix = source.read_text()
    json.loads(matrix)
    if "'''" in matrix:
        raise SystemExit("Matrix contains an unsupported Dart raw-string delimiter.")
    generated = (
        "// Generated by tool/agents/generate_certification.py; do not edit.\n"
        "// Exact docs/verification/agent-certification-matrix.json snapshot.\n"
        "const agentCertificationBundledJson = r'''" + matrix + "''';\n"
    )
    if args.check:
        if not target.exists() or target.read_text() != generated:
            raise SystemExit("Certification snapshot is stale; run the generator.")
        print("Certification snapshot matches the reviewed matrix.")
    else:
        target.write_text(generated)


if __name__ == "__main__":
    main()
