#!/usr/bin/env bash
# ubuntu-opencode.sh — install and manage an OpenCode server on Ubuntu/Linux.
#
# Runs OpenCode as a per-user systemd service so it survives terminal exits
# and reboots without root. Safe to re-run: every subcommand is idempotent.
#
#   bash ubuntu-opencode.sh install    # install/refresh OpenCode + the service
#   bash ubuntu-opencode.sh start      # start the service
#   bash ubuntu-opencode.sh stop       # stop the service
#   bash ubuntu-opencode.sh restart    # restart the service
#   bash ubuntu-opencode.sh status     # service state and listening check
#   bash ubuntu-opencode.sh logs       # follow the server log
#   bash ubuntu-opencode.sh update     # upgrade OpenCode, then restart
#
# Configuration (environment variables, all optional):
#   OPENCODE_PORT      port to listen on            (default 4096)
#   OPENCODE_HOSTNAME  address to bind              (default 0.0.0.0)
#
# Full walkthrough: docs/ubuntu-host.md in https://github.com/Eslamasabry/oc_app
set -euo pipefail

readonly SERVICE_NAME="opencode-serve"
readonly PORT="${OPENCODE_PORT:-4096}"
readonly BIND_HOST="${OPENCODE_HOSTNAME:-0.0.0.0}"
readonly UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
readonly UNIT_FILE="$UNIT_DIR/$SERVICE_NAME.service"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

usage() {
  sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
}

require_systemd_user() {
  command -v systemctl >/dev/null 2>&1 ||
    fail "systemd is required. On WSL or containers, run 'opencode serve' directly instead."
  systemctl --user show-environment >/dev/null 2>&1 ||
    fail "The systemd user manager is not reachable. Log in as this user (not via 'su') and retry."
}

find_opencode() {
  local candidate
  for candidate in \
    "$(command -v opencode 2>/dev/null || true)" \
    "$HOME/.opencode/bin/opencode" \
    "$HOME/.local/bin/opencode" \
    "$HOME/.bun/bin/opencode"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

install_opencode_if_missing() {
  if find_opencode >/dev/null; then
    echo "==> OpenCode is already installed: $(find_opencode)"
    return
  fi
  echo "==> Installing OpenCode with the official installer"
  curl -fsSL https://opencode.ai/install | bash
  find_opencode >/dev/null ||
    fail "The installer finished but 'opencode' was not found. Open a new shell and re-run this script."
}

write_unit() {
  local opencode_bin
  opencode_bin="$(find_opencode)" || fail "OpenCode is not installed. Run: bash $0 install"
  mkdir -p "$UNIT_DIR"
  cat >"$UNIT_FILE" <<UNIT
# Generated by ubuntu-opencode.sh — safe to re-run 'install' to refresh.
[Unit]
Description=OpenCode server for phone and remote clients
After=network-online.target

[Service]
ExecStart=$opencode_bin serve --hostname $BIND_HOST --port $PORT
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  echo "==> Wrote $UNIT_FILE (bind $BIND_HOST, port $PORT)"
}

post_install_hints() {
  cat <<HINTS

Next steps:
  - Keep the server running after you log out:
      loginctl enable-linger "$USER"
  - If a firewall is active, allow the port for your local network, e.g.:
      sudo ufw allow "$PORT"/tcp
  - Connect the phone to http://<this-machine's-LAN-IP>:$PORT
HINTS
}

listening_check() {
  if command -v ss >/dev/null 2>&1 && ss -ltn 2>/dev/null | grep -q ":$PORT "; then
    echo "==> Listening on port $PORT"
  else
    echo "==> Nothing is listening on port $PORT yet"
  fi
}

cmd_install() {
  require_systemd_user
  install_opencode_if_missing
  write_unit
  systemctl --user enable --now "$SERVICE_NAME"
  systemctl --user --no-pager --full status "$SERVICE_NAME" || true
  listening_check
  post_install_hints
}

cmd_update() {
  require_systemd_user
  local opencode_bin
  opencode_bin="$(find_opencode)" || fail "OpenCode is not installed. Run: bash $0 install"
  echo "==> Upgrading OpenCode"
  "$opencode_bin" upgrade
  # The binary path can change across upgrades; refresh the unit before restart.
  write_unit
  systemctl --user restart "$SERVICE_NAME"
  echo "==> Restarted $SERVICE_NAME"
  listening_check
}

main() {
  local command="${1:-}"
  case "$command" in
    install) cmd_install ;;
    start)
      require_systemd_user
      systemctl --user start "$SERVICE_NAME"
      listening_check
      ;;
    stop)
      require_systemd_user
      systemctl --user stop "$SERVICE_NAME"
      ;;
    restart)
      require_systemd_user
      systemctl --user restart "$SERVICE_NAME"
      listening_check
      ;;
    status)
      require_systemd_user
      systemctl --user --no-pager --full status "$SERVICE_NAME" || true
      listening_check
      ;;
    logs)
      require_systemd_user
      journalctl --user -u "$SERVICE_NAME" -f
      ;;
    update) cmd_update ;;
    *)
      usage
      exit 64
      ;;
  esac
}

main "$@"
